"""Sample book for MEM Digital. Every value is realistic, none are real.

Dates are anchored to the current day so the dashboards demonstrate the
mechanics (aging, silence, deadline risk) whenever the console is opened.
Wipe it with the "Reset book" action and the sample flag flips to false.
"""

from __future__ import annotations

import copy

from datetime import date, timedelta

from .store import today


def d(offset: int) -> str:
    return (today() + timedelta(days=offset)).isoformat()


def build(name: str):
    """Fresh, independent copy of the requested collection."""
    value = {
        "settings": _settings,
        "clients": _clients,
        "invoices": _invoices,
        "projects": _projects,
        "messages": _messages,
    }[name]
    return copy.deepcopy(value() if callable(value) else value)


def _settings():
    return {
        "sample_data": True,
        "agency": {
            "name": "MEM Digital",
            "owner": "Marouane El Mouhib",
            "email": "hello@memdigital.studio",
            "phone": "+1 (555) 014-8802",
        "address": "Remote-first · serving US, EU & MENA",
        "tax_id": "TAX-0000000",
        "website": "memdigital.studio",
        "base_currency": "USD",
        },
        "brand_voice": "Confident. Cinematic. Direct. Outcomes over hours.",
        "default_language": "EN",
        "supported_languages": ["EN", "ES"],
        "currency": "USD",
        "fx_rates": {"USD": 1.0, "EUR": 1.08, "GBP": 1.27, "AED": 0.27, "MAD": 0.10, "MXN": 0.058},
        "invoice": {"prefix": "MEM", "next_number": 4, "default_terms": "Net 14", "tax_rate": 0.0},
        "targets": {"monthly_revenue": 18000, "quarterly_revenue": 54000},
        "cadence_days": {"Lead": 3, "Contacted": 5, "Proposal Sent": 4, "Active": 7, "Completed": 21, "Upsell": 14},
        "reminder_policy": [
            {"tier": 1, "trigger": "-2 days to +7 days", "tone": "Friendly admin nudge", "escalation": "None"},
            {"tier": 2, "trigger": "8-21 days", "tone": "Firm, decision-forcing", "escalation": "Request payment date"},
            {"tier": 3, "trigger": "22+ days", "tone": "Formal final notice", "escalation": "Prepay terms + pause work"},
        ],
    }


_clients = [
    {
        "id": "C-001",
        "name": "Daniel Voss",
        "company": "Nordwind Media",
        "email": "daniel@nordwindmedia.com",
        "phone": "+1 415 555 0117",
        "role": "CMO",
        "location": "Austin, US",
        "language": "EN",
        "stage": "Active",
        "tags": ["retainer", "slow payer"],
        "deal_value": 57600,
        "currency": "USD",
        "since": d(-410),
        "source": "Referral",
        "timezone": "CST",
        "communication_style": "Executive brevity. Reads the headline, forwards the detail. Hates being CC'd on noise.",
        "preferences": ["Numbers over adjectives", "Friday summaries", "Slack over email"],
        "payment_behaviour": "Slow but reliable — pays 3-4 weeks late, always in full.",
        "notes": "Q3 retainer renewal is the upgrade window. Wants a podcast arm in 2027 budget.",
        "last_contact": d(-9),
        "next_action": {"note": "Send Q4 plan + renewal options", "due": d(2)},
        "stage_history": [
            {"from": "Lead", "to": "Contacted", "date": d(-410), "value": 57600},
            {"from": "Contacted", "to": "Proposal Sent", "date": d(-395), "value": 57600},
            {"from": "Proposal Sent", "to": "Active", "date": d(-380), "value": 57600},
        ],
    },
    {
        "id": "C-002",
        "name": "Lucía Ferrer",
        "company": "Casa Ferrer",
        "email": "lucia@casaferrer.es",
        "phone": "+34 600 555 018",
        "role": "Founder",
        "location": "Madrid, ES",
        "language": "ES",
        "stage": "Proposal Sent",
        "tags": ["altura", "DTC"],
        "deal_value": 24000,
        "currency": "EUR",
        "since": d(-64),
        "source": "LinkedIn",
        "timezone": "CET",
        "communication_style": "Visual thinker. Wants the story before the spreadsheet. Replies in voice notes.",
        "preferences": ["Spanish-first", "Moodboards", "WhatsApp for quick approvals"],
        "payment_behaviour": "Pays on time when the invoice is in Spanish. Ignores English ones.",
        "notes": "Proposal for a full rebrand + launch campaign. Wants to be live in 3 weeks — timeline needs a reality check.",
        "last_contact": d(-16),
        "next_action": {"note": "Decision nudge on proposal — offer 15-min call", "due": d(-3)},
        "stage_history": [
            {"from": "Lead", "to": "Contacted", "date": d(-64), "value": 24000},
            {"from": "Contacted", "to": "Proposal Sent", "date": d(-16), "value": 24000},
        ],
    },
    {
        "id": "C-003",
        "name": "Omar Haddad",
        "company": "Haddad Hospitality",
        "email": "omar@haddadhospitality.ae",
        "phone": "+971 50 555 0142",
        "role": "Group Marketing Director",
        "location": "Dubai, AE",
        "language": "EN",
        "stage": "Active",
        "tags": ["multi-property", "scope creep"],
        "deal_value": 42000,
        "currency": "AED",
        "since": d(-180),
        "source": "Instagram",
        "timezone": "GST",
        "communication_style": "Direct, fast, transactional. Approves in one word. Expects the same.",
        "preferences": ["Arabic greetings land well", "No long decks", "Sunday working week"],
        "payment_behaviour": "Pays early — wants suppliers who move fast.",
        "notes": "Third property added scope outside the SOW. Change orders ready to bill.",
        "last_contact": d(-4),
        "next_action": {"note": "Push change order HAD-CO-02 to invoice", "due": d(1)},
        "stage_history": [
            {"from": "Lead", "to": "Contacted", "date": d(-180), "value": 42000},
            {"from": "Proposal Sent", "to": "Active", "date": d(-160), "value": 42000},
        ],
    },
    {
        "id": "C-004",
        "name": "Amelia Chen",
        "company": "Pureform Studio",
        "email": "amelia@pureform.studio",
        "phone": "+1 628 555 0193",
        "role": "Creative Director",
        "location": "San Francisco, US",
        "language": "EN",
        "stage": "Completed",
        "tags": ["brand-film"],
        "deal_value": 8500,
        "currency": "USD",
        "since": d(-232),
        "source": "Referral",
        "timezone": "PST",
        "communication_style": "Detail-obsessed on craft, loose on process. Needs deadline pressure to approve.",
        "preferences": ["Frame.io review links", "Explicit version numbers"],
        "payment_behaviour": "Immediate. Wire clears same week, every time.",
        "notes": "Delivered brand film, results strong. Perfect testimonial + case study candidate. Unsold retainer.",
        "last_contact": d(-30),
        "next_action": {"note": "Testimonial ask + retainer conversation", "due": d(3)},
        "stage_history": [
            {"from": "Lead", "to": "Proposal Sent", "date": d(-232), "value": 8500},
            {"from": "Proposal Sent", "to": "Active", "date": d(-226), "value": 8500},
            {"from": "Active", "to": "Completed", "date": d(-21), "value": 8500},
        ],
    },
    {
        "id": "C-005",
        "name": "Marta Ruiz",
        "company": "Vega Health",
        "email": "marta.ruiz@vegahealth.com",
        "phone": "+34 611 555 027",
        "role": "Head of Growth",
        "location": "Barcelona, ES",
        "language": "ES",
        "stage": "Upsell",
        "tags": ["retainer", "healthtech", "expansion"],
        "deal_value": 36000,
        "currency": "EUR",
        "since": d(-300),
        "source": "Referral",
        "timezone": "CET",
        "communication_style": "Data-heavy. Wants the model, not the opinion. Challenges every number — come armed.",
        "preferences": ["Spanish-first", "Dashboard screenshots", "Wednesday calls"],
        "payment_behaviour": "On time, every time.",
        "notes": "Upsell candidate: second retainer line to cover paid social. Strong case study material.",
        "last_contact": d(-3),
        "next_action": {"note": "Present retainer expansion at 10% uplift", "due": d(1)},
        "stage_history": [
            {"from": "Lead", "to": "Contacted", "date": d(-300), "value": 36000},
            {"from": "Contacted", "to": "Active", "date": d(-285), "value": 36000},
            {"from": "Active", "to": "Completed", "date": d(-40), "value": 36000},
            {"from": "Completed", "to": "Upsell", "date": d(-14), "value": 36000},
        ],
    },
]


_invoices = [
    {
        "id": "MEM-2026-001",
        "client_id": "C-001",
        "project_id": "P-001",
        "issue_date": d(-96),
        "due_date": d(-82),
        "currency": "USD",
        "terms": "Net 14",
        "status": "sent",
        "tax_rate": 0.0,
        "discount": 0,
        "notes": "Nordwind retainer — month 1",
        "items": [{"desc": "Retainer — strategy, content & paid (month 1)", "qty": 1, "rate": 4800, "unit": "mo"}],
        "payments": [{"date": d(-79), "amount": 4800, "method": "wire", "note": "Paid in full"}],
        "reminders": [],
    },
    {
        "id": "MEM-2026-002",
        "client_id": "C-001",
        "project_id": "P-001",
        "issue_date": d(-66),
        "due_date": d(-52),
        "currency": "USD",
        "terms": "Net 14",
        "status": "sent",
        "tax_rate": 0.0,
        "discount": 0,
        "notes": "Nordwind retainer — month 2",
        "items": [{"desc": "Retainer — strategy, content & paid (month 2)", "qty": 1, "rate": 4800, "unit": "mo"}],
        "payments": [{"date": d(-21), "amount": 2400, "method": "wire", "note": "Half now, half on month 3"}],
        "reminders": [{"date": d(-38), "tier": 1, "channel": "email"}, {"date": d(-24), "tier": 2, "channel": "email"}],
    },
    {
        "id": "MEM-2026-003",
        "client_id": "C-001",
        "project_id": "P-001",
        "issue_date": d(-77),
        "due_date": d(-63),
        "currency": "USD",
        "terms": "Net 14",
        "status": "sent",
        "tax_rate": 0.0,
        "discount": 0,
        "notes": "Nordwind retainer — month 3",
        "items": [{"desc": "Retainer — strategy, content & paid (month 3)", "qty": 1, "rate": 4800, "unit": "mo"}],
        "payments": [],
        "reminders": [{"date": d(-44), "tier": 2, "channel": "email"}, {"date": d(-30), "tier": 3, "channel": "email"}],
    },
    {
        "id": "MEM-2026-004",
        "client_id": "C-003",
        "project_id": "P-002",
        "issue_date": d(-48),
        "due_date": d(-34),
        "currency": "AED",
        "terms": "Net 14",
        "status": "sent",
        "tax_rate": 0.05,
        "discount": 0,
        "notes": "Haddad — property 1 & 2 launch sprint",
        "items": [
            {"desc": "Launch sprint — property 1 (strategy + creative)", "qty": 1, "rate": 18000, "unit": "fixed"},
            {"desc": "Property 2 social rollout", "qty": 1, "rate": 6000, "unit": "fixed"},
        ],
        "payments": [{"date": d(-33), "amount": 21000, "method": "transfer", "note": "Partial — remainder held for snag list"}],
        "reminders": [{"date": d(-20), "tier": 1, "channel": "email"}],
    },
    {
        "id": "MEM-2026-005",
        "client_id": "C-005",
        "project_id": "P-004",
        "issue_date": d(-38),
        "due_date": d(-24),
        "currency": "EUR",
        "terms": "Net 14",
        "status": "sent",
        "tax_rate": 0.0,
        "discount": 0,
        "notes": "Vega Health — content engine, phase 1",
        "items": [{"desc": "Content engine — 12 assets + distribution", "qty": 1, "rate": 7200, "unit": "fixed"}],
        "payments": [],
        "reminders": [{"date": d(-14), "tier": 1, "channel": "email"}, {"date": d(-7), "tier": 2, "channel": "email"}],
    },
    {
        "id": "MEM-2026-006",
        "client_id": "C-004",
        "project_id": "P-003",
        "issue_date": d(-30),
        "due_date": d(-16),
        "currency": "USD",
        "terms": "Net 14",
        "status": "paid",
        "tax_rate": 0.0,
        "discount": 0,
        "source": "manual",
        "notes": "Pureform — brand film, final",
        "items": [{"desc": "Brand film — edit, grade, sound & delivery", "qty": 1, "rate": 8500, "unit": "fixed"}],
        "payments": [{"date": d(-24), "amount": 8500, "method": "wire", "note": "Paid on receipt"}],
        "reminders": [],
    },
    {
        "id": "MEM-2026-007",
        "client_id": "C-003",
        "project_id": "P-002",
        "issue_date": d(-9),
        "due_date": d(5),
        "currency": "AED",
        "terms": "Net 14",
        "status": "sent",
        "tax_rate": 0.05,
        "discount": 0,
        "notes": "Haddad — change order HAD-CO-01 (third property)",
        "items": [{"desc": "Property 3 creative adaptation", "qty": 1, "rate": 3200, "unit": "fixed"}],
        "payments": [],
        "reminders": [],
    },
    {
        "id": "MEM-2026-008",
        "client_id": "C-005",
        "project_id": "P-004",
        "issue_date": d(-2),
        "due_date": d(12),
        "currency": "EUR",
        "terms": "Net 14",
        "status": "draft",
        "tax_rate": 0.0,
        "discount": 0,
        "notes": "Vega — retainer conversion, month 1",
        "items": [{"desc": "Growth retainer — month 1", "qty": 1, "rate": 3000, "unit": "mo"}],
        "payments": [],
        "reminders": [],
    },
]


_projects = [
    {
        "id": "P-001",
        "client_id": "C-001",
        "name": "Nordwind Retainer — Q4 Sprint",
        "status": "Active",
        "start": d(-96),
        "due": d(9),
        "budget": 14400,
        "currency": "USD",
        "hourly_rate": 110,
        "included_revisions": 2,
        "scope_summary": "Monthly retainer: strategy, 8 content assets, paid media management.",
        "tasks": [
            {"id": "T-001", "name": "Q4 content calendar", "status": "Done", "progress": 100, "due": d(-40), "estimated_hours": 10, "logged_hours": 9, "assignee": "MEM"},
            {"id": "T-002", "name": "Paid media audit", "status": "Done", "progress": 100, "due": d(-25), "estimated_hours": 8, "logged_hours": 11, "assignee": "MEM"},
            {"id": "T-003", "name": "Content batch — month 3", "status": "In Progress", "progress": 60, "due": d(-2), "estimated_hours": 16, "logged_hours": 12, "assignee": "MEM"},
            {"id": "T-004", "name": "Podcast pilot script", "status": "Not Started", "progress": 0, "due": d(5), "estimated_hours": 12, "logged_hours": 4, "assignee": "MEM"},
            {"id": "T-005", "name": "Performance review + renewal deck", "status": "Not Started", "progress": 0, "due": d(9), "estimated_hours": 6, "logged_hours": 0, "assignee": "MEM"},
        ],
        "deliverables": [
            {"name": "Q4 content calendar", "status": "Delivered", "due": d(-38), "revisions": 2, "approval": {"state": "approved", "requested": d(-45), "decided": d(-40)}},
            {"name": "Month 3 content batch", "status": "In Progress", "due": d(1), "revisions": 1, "approval": {"state": "none"}},
            {"name": "Podcast pilot script", "status": "Planned", "due": d(6), "revisions": 0, "approval": {"state": "none"}},
        ],
        "time_entries": [
            {"id": "TE-001", "date": d(-34), "task_id": "T-001", "hours": 9, "note": "Calendar build", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-002", "date": d(-22), "task_id": "T-002", "hours": 11, "note": "Audit + reporting rebuild", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-003", "date": d(-6), "task_id": "T-003", "hours": 12, "note": "Batch production (covered by month-3 retainer)", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-004", "date": d(-3), "task_id": "T-004", "hours": 4, "note": "Podcast research (never scoped)", "in_scope": False, "billable": True, "invoiced": False},
        ],
        "change_orders": [],
        "risks": ["Podcast pilot is outside the retainer SOW — raise change order."],
        "health_flag": "At Risk",
        "scope_exposure": True,
    },
    {
        "id": "P-002",
        "client_id": "C-003",
        "name": "Haddad — Multi-Property Launch",
        "status": "Active",
        "start": d(-60),
        "due": d(-2),
        "budget": 24000,
        "currency": "AED",
        "hourly_rate": 420,
        "included_revisions": 2,
        "scope_summary": "Launch campaign for property 1 & 2: strategy, creative, social rollout.",
        "tasks": [
            {"id": "T-011", "name": "Property 1 launch film", "status": "Done", "progress": 100, "due": d(-30), "estimated_hours": 20, "logged_hours": 24},
            {"id": "T-012", "name": "Property 2 social rollout", "status": "Done", "progress": 100, "due": d(-16), "estimated_hours": 14, "logged_hours": 15},
            {"id": "T-013", "name": "Property 3 adaptation (unscheduled)", "status": "In Progress", "progress": 45, "due": d(4), "estimated_hours": 12, "logged_hours": 14},
            {"id": "T-014", "name": "Launch performance report", "status": "Blocked", "progress": 0, "due": d(1), "estimated_hours": 6, "logged_hours": 0},
        ],
        "deliverables": [
            {"name": "Property 1 launch film", "status": "Delivered", "due": d(-30), "revisions": 4, "approval": {"state": "approved", "requested": d(-42), "decided": d(-38)}},
            {"name": "Property 2 creative set", "status": "Delivered", "due": d(-14), "revisions": 2, "approval": {"state": "approved", "requested": d(-20), "decided": d(-18)}},
            {"name": "Property 3 creative adaptation", "status": "In Review", "due": d(4), "revisions": 0, "approval": {"state": "pending", "requested": d(-8)}},
        ],
        "time_entries": [
            {"id": "TE-011", "date": d(-34), "task_id": "T-011", "hours": 24, "note": "Film production", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-012", "date": d(-18), "task_id": "T-012", "hours": 15, "note": "Social rollout", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-013", "date": d(-5), "task_id": "T-013", "hours": 14, "note": "Property 3 creative — not in SOW", "in_scope": False, "billable": True, "invoiced": False},
            {"id": "TE-014", "date": d(-2), "task_id": "T-014", "hours": 0, "note": "Blocked: awaiting property 3 media plan", "in_scope": True, "billable": True, "invoiced": False},
        ],
        "change_orders": [
            {"id": "HAD-CO-01", "title": "Property 3 creative adaptation", "amount": 3200, "hours": 12, "status": "Billed", "date": d(-12)},
            {"id": "HAD-CO-02", "title": "Property 3 media plan + rollout", "amount": 2800, "hours": 10, "status": "Approved", "date": d(-4)},
        ],
        "risks": ["Project deadline passed — report blocked on client media plan.", "Approved change order HAD-CO-02 not yet invoiced."],
        "health_flag": "At Risk",
        "scope_exposure": True,
    },
    {
        "id": "P-003",
        "client_id": "C-004",
        "name": "Pureform — Brand Film",
        "status": "Completed",
        "start": d(-70),
        "due": d(-28),
        "budget": 8500,
        "currency": "USD",
        "hourly_rate": 125,
        "included_revisions": 3,
        "scope_summary": "60-second brand film: concept, shoot, edit, grade.",
        "tasks": [
            {"id": "T-021", "name": "Concept + treatment", "status": "Done", "progress": 100, "due": d(-58), "estimated_hours": 8, "logged_hours": 7},
            {"id": "T-022", "name": "Shoot (2 days)", "status": "Done", "progress": 100, "due": d(-45), "estimated_hours": 24, "logged_hours": 26},
            {"id": "T-023", "name": "Edit + grade", "status": "Done", "progress": 100, "due": d(-32), "estimated_hours": 22, "logged_hours": 24},
            {"id": "T-024", "name": "Delivery + masters", "status": "Done", "progress": 100, "due": d(-28), "estimated_hours": 4, "logged_hours": 3},
        ],
        "deliverables": [
            {"name": "Brand film — final master", "status": "Delivered", "due": d(-28), "revisions": 3, "approval": {"state": "approved", "requested": d(-36), "decided": d(-30)}},
        ],
        "time_entries": [
            {"id": "TE-021", "date": d(-50), "task_id": "T-021", "hours": 7, "note": "Treatment", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-022", "date": d(-44), "task_id": "T-022", "hours": 26, "note": "Shoot days", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-023", "date": d(-33), "task_id": "T-023", "hours": 24, "note": "Edit + grade", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-024", "date": d(-29), "task_id": "T-024", "hours": 3, "note": "Mastering", "in_scope": True, "billable": True, "invoiced": True},
        ],
        "change_orders": [],
        "risks": [],
        "health_flag": "Healthy",
        "scope_exposure": False,
    },
    {
        "id": "P-004",
        "client_id": "C-005",
        "name": "Vega Health — Content Engine",
        "status": "Active",
        "start": d(-45),
        "due": d(18),
        "budget": 12000,
        "currency": "EUR",
        "hourly_rate": 95,
        "included_revisions": 2,
        "scope_summary": "12 content assets + distribution engine, phase 1 of retainer conversion.",
        "tasks": [
            {"id": "T-031", "name": "Message architecture", "status": "Done", "progress": 100, "due": d(-35), "estimated_hours": 8, "logged_hours": 8},
            {"id": "T-032", "name": "Asset production (12)", "status": "In Progress", "progress": 70, "due": d(10), "estimated_hours": 24, "logged_hours": 20},
            {"id": "T-033", "name": "Distribution setup", "status": "In Progress", "progress": 30, "due": d(16), "estimated_hours": 10, "logged_hours": 4},
        ],
        "deliverables": [
            {"name": "Message architecture", "status": "Approved", "due": d(-34), "revisions": 1, "approval": {"state": "approved", "requested": d(-38), "decided": d(-35)}},
            {"name": "Content set A (6 assets)", "status": "Awaiting Approval", "due": d(-1), "revisions": 2, "approval": {"state": "pending", "requested": d(-6)}},
            {"name": "Content set B (6 assets)", "status": "In Progress", "due": d(12), "revisions": 0, "approval": {"state": "none"}},
        ],
        "time_entries": [
            {"id": "TE-031", "date": d(-36), "task_id": "T-031", "hours": 8, "note": "Architecture", "in_scope": True, "billable": True, "invoiced": True},
            {"id": "TE-032", "date": d(-10), "task_id": "T-032", "hours": 20, "note": "Asset production", "in_scope": True, "billable": True, "invoiced": False},
            {"id": "TE-033", "date": d(-4), "task_id": "T-033", "hours": 4, "note": "Distribution setup", "in_scope": True, "billable": True, "invoiced": False},
        ],
        "change_orders": [],
        "risks": ["Content set A awaiting approval 6 days — blocks set B production."],
        "health_flag": "Healthy",
        "scope_exposure": False,
    },
]


_messages = [
    {
        "id": "M-001", "client_id": "C-002", "date": d(-16), "channel": "email", "direction": "out",
        "subject": "Casa Ferrer — proposal: rebrand + launch",
        "summary": "Proposal delivered: rebrand + 3-week launch, €24,000, two payment stages.",
    },
    {
        "id": "M-002", "client_id": "C-002", "date": d(-9), "channel": "whatsapp", "direction": "in",
        "subject": "Propuesta recibida",
        "summary": "Lucía confirms receipt, asks whether the timeline can compress to 2 weeks, will discuss with her partner.",
    },
    {
        "id": "M-003", "client_id": "C-002", "date": d(-7), "channel": "email", "direction": "out",
        "subject": "Re: timeline — what a 2-week version actually costs",
        "summary": "Explained the 2-week compression requires paid ad spend pre-approved and a locked brand direction by Friday.",
    },
    {
        "id": "M-004", "client_id": "C-001", "date": d(-9), "channel": "slack", "direction": "in",
        "subject": "Q4 plan",
        "summary": "Daniel wants Q4 plan + renewal options before their board meeting. Asked for the podcast line item.",
    },
    {
        "id": "M-005", "client_id": "C-001", "date": d(-44), "channel": "email", "direction": "out",
        "subject": "Reminder: invoice MEM-2026-003",
        "summary": "Final notice sent on month-3 retainer — $4,800, 30+ days late.",
        "reminder_tier": 3,
    },
    {
        "id": "M-006", "client_id": "C-003", "date": d(-4), "channel": "whatsapp", "direction": "in",
        "subject": "Property 3",
        "summary": "Omar approves HAD-CO-02 (2,800 AED) verbally and wants it live before their weekend.",
    },
    {
        "id": "M-007", "client_id": "C-003", "date": d(-8), "channel": "email", "direction": "out",
        "subject": "Approval needed: Property 3 creative adaptation",
        "summary": "Sent creative for approval — still pending, blocking production.",
    },
    {
        "id": "M-008", "client_id": "C-004", "date": d(-30), "channel": "email", "direction": "out",
        "subject": "Pureform — brand film delivered",
        "summary": "Final masters delivered, invoice cleared same week. Testimonial ask pending.",
    },
    {
        "id": "M-009", "client_id": "C-005", "date": d(-3), "channel": "call", "direction": "out",
        "subject": "Vega — Q1 planning",
        "summary": "Marta open to retainer expansion, wants the model with CAC assumptions before deciding. Wants it in Spanish.",
    },
    {
        "id": "M-010", "client_id": "C-005", "date": d(-6), "channel": "email", "direction": "out",
        "subject": "Approval: Content set A",
        "summary": "Six assets sent for approval, awaiting sign-off before set B goes into production.",
    },
    {
        "id": "M-011", "client_id": "C-005", "date": d(-7), "channel": "email", "direction": "out",
        "subject": "Reminder: invoice MEM-2026-005",
        "summary": "Firm reminder sent — €7,200 now 7 days past due.",
        "reminder_tier": 2,
    },
    {
        "id": "M-012", "client_id": "C-001", "date": d(-2), "channel": "email", "direction": "out",
        "subject": "Q4 plan draft for review",
        "summary": "Draft Q4 plan sent for Daniel's board meeting prep.",
    },
]
